version: '3'
services:
  foobar:
    container_name: foobar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    working_dir: /usr/share/nginx/html/project
    volumes:
      - .:/usr/share/nginx/html/project
